version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: "mongo"
    volumes:
      - "mongodb_data:/data/db"

volumes:
  mongodb_data: {}
